### ISSUE TITLE
Adding Python 3 compatibility

### ISSUE THREAD

**Issue by mwiora** [mwiora/NAMEinator#1]
currently namebench is only runnable with Python 2

**Comment by xeoron** [comment]
I would love a android app port.

**Comment by anthony-wang** [comment]
+1

**Comment by mwiora** [comment]
@xeoron I have some thoughts about an android app for another problem that I have with this project (getting really the latest DNS Servers). 
However due to the problem with always wifi based connections I think the whole application running on android would be not useful - maybe you have arguments that are effective and the current problems will get fixed faster then expected :D 

however - I had an eye on the portability towards python3 and it seems to be a desaster currently. I think we will have to get rid of that Tkinter GUI stuff first before we can upgrade the compatibility. I'll work on that GUI topic and come back to this later on.

**Comment by mwiora** [comment]
I've decided to move all of the functions of namebench 1.3.1 (python) to NAMEinator (go) with the same set of functions. As it is in alpha state maybe not all functions are implemented yet, but considered as planned - have a look to https://github.com/mwiora/NAMEinator and the checklist. closing this issue.
