### ISSUE TITLE
No GUI?

### ISSUE THREAD

**Issue by beeuhtricks** [mwiora/NAMEinator#11]
I'm running on macOS 10.12.3 and I do not get a GUI from ./namebench.py

**Comment by mwiora** [comment]
hi bklebe,

the gui is currently not planned. We'd like to work on the CLI Version and then build a GUI, which is using the CLI in the background.

Cheers,
Matthias

**Comment by bklebe** [comment]
oh! I see. I managed to get a gui by commenting out the mac platform checks, by the way.

**Comment by mwiora** [comment]
ah cool stuff 👍 thanks for posting the solution - maybe you want to obtain the GUI part? ^^ I actually do not have any time to spend on the GUI topic.

**Comment by bklebe** [comment]
I can look into it, sure. I have zero experience with Tk though so it might be a while.
