### ISSUE TITLE
The default site for uploads seems offline

### ISSUE THREAD

**Issue by rbrito** [mwiora/NAMEinator#12]
Hi.

The subject mostly says it all. The site http://namebench.appspot.com/ that is listed when invoking namebench with the --help option gives a 404 message. Perhaps the option should be retired or a substitute site should be found?

Thanks in advance for keeping namebench maintained,

Rogério Brito.

**Comment by dgentry** [comment]
Still offline.  What did it do before?  Just collect stats on which DNS servers were fastest/best?

**Comment by mwiora** [comment]
hi all - thanks for testing and reporting this.
As I do not have the sourcecode that was running on that appspot engine I cannot provide the same page for you.
I actually have another idea regarding the upload results and merging them together with the DNS Server question - I'll keep you up2date and report to you back again as soon as possible.

**Comment by mwiora** [comment]
I've decided to move all of the functions of namebench 1.3.1 (python) to NAMEinator (go) with the same set of functions. As it is in alpha state maybe not all functions are implemented yet, but considered as planned - have a look to https://github.com/mwiora/NAMEinator and the checklist. closing this issue.
