### ISSUE TITLE
Add Markupsafe as python package dependency

### ISSUE THREAD

**Issue by kunstkomputer** [mwiora/NAMEinator#13]
I just cloned the repo from `1.3` branch on b1de8f and installed it running:
`cd namebench`
`pip install .`

This successfully installs the package but running `namebench.py` fails with:
`ImportError: No module named markupsafe`

After installing it manually with: `pip install markupsafe` the script runs successfully.

I'm happy to provide a PR if that is of any help.

**Comment by mwiora** [comment]
I do not get this error - actually if you still want to help just send me the PR and maybe your environment information - thanks man

**Comment by mwiora** [comment]
I've decided to move all of the functions of namebench 1.3.1 (python) to NAMEinator (go) with the same set of functions. As it is in alpha state maybe not all functions are implemented yet, but considered as planned - have a look to https://github.com/mwiora/NAMEinator and the checklist. closing this issue.
