### ISSUE TITLE
Stuck on OSX 10.9.5

### ISSUE THREAD

**Issue by andyRoj4s** [mwiora/NAMEinator#14]
In OS X 10.9.5, it takes 45 minutes to check nameserver availability "(6 threads) [.../4516]", then  it begins sending queries.
Decided to close the app after 2 hours of being stuck with "Sending 250 queries 4 Servers [11/1000]"

**Comment by rbrito** [comment]
Indeed, running namebench takes quite a long time. I wonder what could be made to speed it up...

**Comment by mwiora** [comment]
I've decided to move all of the functions of namebench 1.3.1 (python) to NAMEinator (go) with the same set of functions. As it is in alpha state maybe not all functions are implemented yet, but considered as planned - have a look to https://github.com/mwiora/NAMEinator and the checklist. closing this issue.
