### ISSUE TITLE
exit status 1

### ISSUE THREAD

**Issue by mlasch** [mwiora/NAMEinator#19]
Hi,

I compiled NAMEinator on ubuntu 18.10 with go1.10.4 linux/amd64

When I try to run it, I the the following result:

```
marc@thinkpad2:~/go/bin$ ./NAMEinator 
starting NAMEinator - version 0.3 alpha
understood the following configuration: {numberOfDomains:100 debug:false contest:true nameserver:}
-------------
NOTE: as this is an alpha - we rely on feedback - please report bugs and featurerequests to https://github.com/mwiora/NAMEinator/issues and provide this output
OS: linux ARCH: amd64
-------------
2019/03/07 12:35:23 exit status 1
```

any idea?

**Comment by mwiora** [comment]
thanks man - you are abolutely right!
I could verify the issue and observed that the same happens on other distributions with latest updates applied as nslookup no longer reports the used DNS Server to the application.
I will take care of this this weekend.

Cheers,
µ

**Comment by mwiora** [comment]
hi @mlasch 

could you please obtain the latest version and test it?
Would be happy about feedback!

// µatthias

**Comment by mlasch** [comment]
hey @mwiora 
that was the trick, works nicely.
