### ISSUE TITLE
Files missing from published release

### ISSUE THREAD

**Issue by MaxMilton** [mwiora/NAMEinator#20]
The contents of `datasrc/` are missing from `NAMEinator_0.0.3_linux_amd64.tar.gz`. Had to manually add the 2 files to get the bin to run correctly.

Didn't check the releases for other targets.

**Comment by mwiora** [comment]
Hi @MaxMilton ,

yeah  indeed ;D I always used it via go get so I've never tried to get it running on an non-go instance :D 
I will fix that asap. Great that you got it working anyway. Thanks for notification!

Cheers,
Matthias

**Comment by mwiora** [comment]
fixed with https://github.com/mwiora/NAMEinator/commit/ad9ea76f30654300c02bfa4b855eca0278af082b
hope this helps :)
