### ISSUE TITLE
Document usage of -contest

### ISSUE THREAD

**Issue by guedressel** [mwiora/NAMEinator#25]
I struggled to find the correct way of disabling contest mode.
It's enabled by default, so I had to switch it off.
What I tried:

```
NAMEinator -contest false
NAMEinator -contest off
NAMEinator -contest no
NAMEinator -contest 0
NAMEinator -nocontest
...
```

What actually worked:
```
NAMEinator -contest=false
```

I suggest to document correct usage of `-contest` argument.

**Comment by mwiora** [comment]
closing is seriously a fast thing :D just added the help information - thanks for your contribution!
