### ISSUE TITLE
Update censoring check

### ISSUE THREAD

**Issue by mwiora** [mwiora/NAMEinator#5]
Currenly each search results in false positive censorship-check results:
- The current preferred DNS server.
- www.google.com is hijacked: 74.125.136.106, 74.125.136.105, 74.125.136.99, 74.125.136.103, 74.125.136.147, 74.125.136.104
- google.com appears incorrect: 216.58.211.46
- twitter.com appears incorrect: 104.244.42.193, 104.244.42.65

This seems to be the result of an outdated censorship reference list.

**Comment by rbrito** [comment]
Using Daniel J. Bernstein's tool `dnsq` (a more readable alternative than the popular `dig` tool) and performing the recursive DNS query myself, I can see that, indeed, at least the `google.com` entries are missing and we should update the files under the `config` directory.

**Comment by mwiora** [comment]
I've decided to move all of the functions of namebench 1.3.1 (python) to NAMEinator (go) with the same set of functions. As it is in alpha state maybe not all functions are implemented yet, but considered as planned - have a look to https://github.com/mwiora/NAMEinator and the checklist. closing this issue.
